CONFIG_ZMK_KEYBOARD_NAME="roBa"

CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y

CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_SMART_ALGORITHM=y
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_ALT_REST1_SAMPLE_TIME_MS=20
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=8

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
