CONFIG_ZMK_KEYBOARD_NAME="roBa"
CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=800
CONFIG_PMW3610_ORIENTATION_180=y
CONFIG_PMW3610_POLLING_RATE_125_SW=y
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=60000
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_MOUSE=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_ZMK_SENSORS=y